version: '3'
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    networks:
      testing_net:
        ipv4_address: 172.28.1.5

  api:
    build: ./api
    ports:
      - "3002:3002"
    environment:
      SERVER_PORT: 3002
      THREADS: 2
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16