version: '3'
services:
  api:
    image: blockchainlg/trybe-micro-credentials-api:master
    ports:
      - "3002:3002"
    environment:
      SERVER_PORT: 3002
      THREADS: 4
      HTTPS: 'true'
      DOMAIN: 'trybe.convergence.tech'
      DB_URL: mongodb://169.48.26.229:27017
      SEND_EMAIL: 'true'
      ROPSTEN_ETH_TX: 'true'
      DEPLOYED_ENV: 'prod'
    networks:
      prod_net:
        ipv4_address: 172.28.1.2
  
  db: 
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - /usr/trybe/data:/data/db
    command: mongod --auth
    networks:
        staging_net:
          ipv4_address: 172.28.1.3

networks:
  prod_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16